---
name: Release

on:
  push:
    tags:
      - v*.*.*

env:
  CARGO_TERM_COLOR: always

jobs:
  wait-for-ci:
    name: Wait for CI
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI to pass
        uses: lewagon/wait-on-check-action@v1.5.0
        with:
          ref: ${{ github.sha }}
          running-workflow-name: Wait for CI
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  publish:
    runs-on: ubuntu-latest
    name: Publish Client
    needs: wait-for-ci
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_REGISTRY_TOKEN }}
